name: "godot-ci build-and-release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: Godot8Lumbreras
  PROJECT_PATH: src
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls ~/.local/share/godot/export_templates/
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: GitHub Tag Name
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Setup folders
        run: |
          mkdir -p .godot/editor .godot/imported
          mkdir -v -p build/windows
          echo "$GITHUB_REF" > build/version.txt
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-builds
          path: build