name: "godot-ci build-and-release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GODOT_VERSION: 4.3
  
jobs:
  deploy:
    runs-on: ubuntu-18.04

    container:
      image: barichello/godot-ci:3.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p build/web
      
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-builds
          path: build