name: "godot-ci build-and-release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Godot
        uses: godotengine/godot-action@v1
        with:
          godot-version: '4.3'  # Specify the Godot version you are using

      - name: Build for Windows
        run: godot --headless --export "Windows Desktop" export_presets.cfg
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: godot-build
          path: |
            godot-build